### ISSUE TITLE
Przetestowanie paczki rrt_exploration

### ISSUE THREAD

**Issue by configo** [Bialystok-Dynamics/Dzik#12]
Poprawne wdrożenie paczki i autonomiczne wykonanie przez robota mapy środowiska symulacyjnego.

## Podzadania
- [x] Wczesna konfiguracja środowiska, dodanie stałych punktów określających obszar budowy RRT
- [x] Komunikacja /map z RRT_exploration
- [x] Akcja move_base do poprawy
- [x] Mierzenie czasu od rozpoczęcia mapowania do zakończenia

Branch - [Mary RRT](https://github.com/Bialystok-Dynamics/Dzik/tree/Mary_RRT)

**Comment by configo** [comment]
@MaryM34 opiszesz jaki masz problem aktualnie?

**Comment by MaryM34** [comment]
Pojawil sie problem z odswierzaniem mapy. Mapa buduje sie do pewnego momentu, po czym wystepuje blad:
(czestotliwosc wymagana nie pokrywa sie z rzeczywista)
 [ WARN] [1689940973.148223775, 348.788000000]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.2710 seconds

**Comment by MaryM34** [comment]
Komunikat

[ INFO] [1689941776.080259287, 352.740000000]: Goal reached
Registering Scans:Done

konczy eksploracje robota


(usprawnienie)
poniewaz lidar jest 360 robot moze osiagac wyznaczone punkty rozwojowe tylko w xy bez osiagania zadaengo kierunku

**Comment by MaryM34** [comment]
Algorytm wyznacza punkty rozwojowe w przestrzeni niebezpiecznej (sciana i jej obreb) 

**Dla domyslnych ustawien dwa local planner**

robot nie moze tam dojechac 

zatrzymuje sie wtedy nie wyznacza sciezki nie osiaga celu 



![Image](https://github.com/Bialystok-Dynamics/Dzik/assets/94919634/3f578f17-aac1-4c1c-8df0-08a0c33b2449)



(przestrzen nie pokryta niebieskimi sciezkami jest poza dzialaniem algorytmu robot sie tam nie przemieszcza)

**Comment by configo** [comment]
~~Czeka na #54~~
