### ISSUE TITLE
Autonomiczne mapowanie w środowisku statycznym (symulacja)

### ISSUE THREAD

**Issue by configo** [Bialystok-Dynamics/Dzik#14]
Autonomiczne mapowanie w środowisku symulacyjnym przez oba algorytmy.

## Podzadania
- [x] Symulacja mapowania RRT
- [x] Symulacja mapowania BUG

**Comment by MaryM34** [comment]
carrot planner umozliwia dojazd do punktu najblizej jak to mozliwe, czyli punkt w scianie nie jest przeszkoda :)

**Comment by configo** [comment]
~~Czeka na #54~~
