### ISSUE TITLE
Pojawil sie problem z odswierzaniem mapy. Mapa buduje sie do pewnego momentu, po czym wystepuje blad:

### ISSUE THREAD

**Issue by MaryM34** [Bialystok-Dynamics/Dzik#15]
Pojawil sie problem z odswierzaniem mapy. Mapa buduje sie do pewnego momentu, po czym wystepuje blad:
(czestotliwosc wymagana nie pokrywa sie z rzeczywista)
 [ WARN] [1689940973.148223775, 348.788000000]: Map update loop missed its desired rate of 10.0000Hz... the loop actually took 0.2710 seconds

_Originally posted by @MaryM34 in https://github.com/Bialystok-Dynamics/Dzik/issues/12#issuecomment-1645481651_

**Comment by configo** [comment]
Duplikat.

Oryginał: #12

**Comment by configo** [comment]
Duplicate of #12
